### ISSUE TITLE
@at-root scss 사용

### ISSUE THREAD

**Issue by shldhee** [shldhee/note#10]
``` scss
.keytalk-ranking-item {
  max-width: 1276px;
  overflow: hidden;
  &__info {
    cursor: pointer;
    position: relative;
    padding: 12px 16px 8px;
    // height: 66px;
    background: #ffffff;
    border: 1px solid #e9ecef;
    @at-root .is-active & {
      border-color: var(--primary-color);
      background-color: #f9f7ff;
    }
  }
}
```

``` css
.is-active .keytalk-ranking-item__info {
    border-color: var(--primary-color);
    background-color: #f9f7ff;
}
```
