### ISSUE TITLE
image width height css aspect-ratio

### ISSUE THREAD

**Issue by shldhee** [shldhee/note#27]
``` css
<style>
  img {
    width: 100%;
    height: auto;
    aspect-ratio: attr(width) / attr(height);
  } 
</style>
<img src="hero_image.jpg" alt="" width="500" height="500">
```

https://www.smashingmagazine.com/2020/03/setting-height-width-images-important-again/
